// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.intera.roostrap.domain;

import com.intera.roostrap.domain.Country;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Country_Roo_Configurable {
    
    declare @type: Country: @Configurable;
    
}
